"""pipeline_id on delete set null

Revision ID: 031bc0cba40f
Revises: a1b2c3d4e5f6
Create Date: 2026-09-29 10:39:28.444380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '031bc0cba40f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'pipeline_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('runs_pipeline_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'pipelines', ['pipeline_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_pipeline_id_fkey'), 'runs', 'pipelines', ['pipeline_id'], ['id'])
    op.alter_column('runs', 'pipeline_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
