"""remove knowledge_bases table

Revision ID: 1dea09fdabe9
Revises: 8ea7f3bb4e3c
Create Date: 2026-10-03 20:01:55.687454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dea09fdabe9'
down_revision: Union[str, None] = '8ea7f3bb4e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_kb_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'kb_id')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_constraint(op.f('documents_kb_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'kb_id')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('kb_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_kb_id_fkey'), 'documents', 'knowledge_bases', ['kb_id'], ['id'])
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.add_column('agents', sa.Column('kb_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agents_kb_id_fkey'), 'agents', 'knowledge_bases', ['kb_id'], ['id'])
    op.create_table('knowledge_bases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_bases_pkey'))
    )
    # ### end Alembic commands ###
