"""add agent_tool

Revision ID: 3f403cd6dfde
Revises: 1dea09fdabe9
Create Date: 2026-10-05 14:11:26.790989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3f403cd6dfde'
down_revision: Union[str, None] = '1dea09fdabe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('agent_tool', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'agent_tool')
    # ### end Alembic commands ###
