"""add output

Revision ID: 97a76ffcef33
Revises: a3e7c9d1f5b8
Create Date: 2026-09-06 01:07:30.870676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97a76ffcef33'
down_revision: Union[str, None] = 'a3e7c9d1f5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('output', sa.JSON(), nullable=True))
    op.alter_column('runs', 'pipeline',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'pipeline',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('runs', 'output')
    # ### end Alembic commands ###
