"""remove chunk_index

Revision ID: e349b2f48489
Revises: 74b2c518b1b2
Create Date: 2026-10-03 13:18:45.448121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e349b2f48489'
down_revision: Union[str, None] = '74b2c518b1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
