"""add upload table

Revision ID: f58279d0ec28
Revises: e5f6a7b8c9d0
Create Date: 2026-09-24 14:11:50.579094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f58279d0ec28'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_kb_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'knowledge_bases', ['kb_id'], ['id'])
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_chunks_embedding'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('documents_kb_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['id'])
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_kb_id_fkey'), 'documents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chunks_embedding'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.alter_column('chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_kb_id_fkey'), 'agents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
